---
version: "2"
linters:
  enable:
    - "bidichk"
    - "bodyclose"
    - "depguard"
    - "errcheck"
    - "errname"
    - "errorlint"
    - "gocritic"
    - "goprintffuncname"
    - "gosec"
    - "govet"
    - "importas"
    - "ineffassign"
    - "makezero"
    - "perfsprint"
    - "prealloc"
    - "predeclared"
    - "promlinter"
    - "revive"
    - "rowserrcheck"
    - "spancheck"
    - "staticcheck"
    - "tagalign"
    - "testifylint"
    - "tparallel"
    - "unconvert"
    - "usetesting"
    - "wastedassign"
    - "whitespace"
    - "unused"
  exclusions:
    generated: "lax"
    presets:
      - "comments"
      - "common-false-positives"
      - "legacy"
      - "std-error-handling"
    paths:
      - "third_party$"
      - "builtin$"
      - "examples$"
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: "k8s.io/utils/strings/slices$"
              desc: "use github.com/samber/lo"
    staticcheck:
      checks:
        - "all"
formatters:
  enable:
    - "gci"
    - "gofmt"
    - "gofumpt"
    - "goimports"
  settings:
    gofmt:
      rewrite-rules:
        - pattern: "interface{}"
          replacement: "any"
        - pattern: "a[b:len(a)]"
          replacement: "a[b:]"
    gci:
      sections:
        - "standard"
        - "default"
        - "prefix(github.com/authzed)"
        - "localmodule"
    goimports:
      local-prefixes:
        - "github.com/authzed/zed"
  exclusions:
    generated: "lax"
    paths:
      - "third_party$"
      - "builtin$"
      - "examples$"
