---
builds:
  - id: "linux-amd64"
    goos: ["linux"]
    goarch: ["amd64"]
    env:
      - "CC=gcc"
      - "CGO_ENABLED=1"
    main: &main "./cmd/zed"
    binary: &binary "zed"
    mod_timestamp: &mod_timestamp "{{ .CommitTimestamp }}"
    flags: &flags ["-trimpath"]
    asmflags: &asmflags ["all=-trimpath={{ .Env.GITHUB_WORKSPACE }}"]
    gcflags: &gcflags ["all=-trimpath={{ .Env.GITHUB_WORKSPACE }}"]
    ldflags: &ldflags
      - "-s -w"
      - "-X github.com/jzelinskie/cobrautil.Version={{ .Version }}"
  - id: "linux-arm64"
    goos: ["linux"]
    goarch: ["arm64"]
    env:
      - "CC=aarch64-linux-gnu-gcc"
      - "CGO_ENABLED=1"
    main: *main
    binary: *binary
    mod_timestamp: *mod_timestamp
    flags: *flags
    asmflags: *asmflags
    gcflags: *gcflags
    ldflags: *ldflags

dockers:
  # AMD64
  - image_templates:
      - &amd_image_quay "quay.io/authzed/zed:v{{ .Version }}-amd64"
      - &amd_image_gh "ghcr.io/authzed/zed:v{{ .Version }}-amd64"
      - &amd_image_dh "authzed/zed:v{{ .Version }}-amd64"
    ids: ["linux-amd64"]
    dockerfile: &dockerfile "Dockerfile.release"
    goos: "linux"
    goarch: "amd64"
    use: "buildx"
    build_flag_templates:
      - "--platform=linux/amd64"
  # AMD64 (debug)
  - image_templates:
      - &amd_debug_image_quay "quay.io/authzed/zed:v{{ .Version }}-amd64-debug"
      - &amd_debug_image_gh "ghcr.io/authzed/zed:v{{ .Version }}-amd64-debug"
      - &amd_debug_image_dh "authzed/zed:v{{ .Version }}-amd64-debug"
    ids: ["linux-amd64"]
    dockerfile: &dockerfile "Dockerfile.release"
    goos: "linux"
    goarch: "amd64"
    use: "buildx"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--build-arg=BASE=cgr.dev/chainguard/alpine-base:latest"
  # ARM64
  - image_templates:
      - &arm_image_quay "quay.io/authzed/zed:v{{ .Version }}-arm64"
      - &arm_image_gh "ghcr.io/authzed/zed:v{{ .Version }}-arm64"
      - &arm_image_dh "authzed/zed:v{{ .Version }}-arm64"
    ids: ["linux-arm64"]
    dockerfile: *dockerfile
    goos: "linux"
    goarch: "arm64"
    use: "buildx"
    build_flag_templates:
      - "--platform=linux/arm64"
  # ARM64 (debug)
  - image_templates:
      - &arm_debug_image_quay "quay.io/authzed/zed:v{{ .Version }}-arm64-debug"
      - &arm_debug_image_gh "ghcr.io/authzed/zed:v{{ .Version }}-arm64-debug"
      - &arm_debug_image_dh "authzed/zed:v{{ .Version }}-arm64-debug"
    ids: ["linux-arm64"]
    dockerfile: *dockerfile
    goos: "linux"
    goarch: "arm64"
    use: "buildx"
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--build-arg=BASE=cgr.dev/chainguard/alpine-base:latest"

docker_manifests:
  # Quay
  - name_template: "quay.io/authzed/zed:v{{ .Version }}"
    image_templates: [*amd_image_quay, *arm_image_quay]
  - name_template: "quay.io/authzed/zed:latest"
    image_templates: [*amd_image_quay, *arm_image_quay]
  # GitHub Registry
  - name_template: "ghcr.io/authzed/zed:v{{ .Version }}"
    image_templates: [*amd_image_gh, *arm_image_gh]
  - name_template: "ghcr.io/authzed/zed:latest"
    image_templates: [*amd_image_gh, *arm_image_gh]
  # Docker Hub
  - name_template: "authzed/zed:v{{ .Version }}"
    image_templates: [*amd_image_dh, *arm_image_dh]
  - name_template: "authzed/zed:latest"
    image_templates: [*amd_image_dh, *arm_image_dh]
  # Debug Images:
  # Quay (debug)
  - name_template: "quay.io/authzed/zed:v{{ .Version }}-debug"
    image_templates: [*amd_debug_image_quay, *arm_debug_image_quay]
  - name_template: "quay.io/authzed/zed:latest-debug"
    image_templates: [*amd_debug_image_quay, *arm_debug_image_quay]
  # GitHub Registry
  - name_template: "ghcr.io/authzed/zed:v{{ .Version }}-debug"
    image_templates: [*amd_debug_image_gh, *arm_debug_image_gh]
  - name_template: "ghcr.io/authzed/zed:latest-debug"
    image_templates: [*amd_debug_image_gh, *arm_debug_image_gh]
  # Docker Hub
  - name_template: "authzed/zed:v{{ .Version }}-debug"
    image_templates: [*amd_debug_image_dh, *arm_debug_image_dh]
  - name_template: "authzed/zed:latest-debug"
    image_templates: [*amd_debug_image_dh, *arm_debug_image_dh]
release:
  disable: true
