// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/authzed/authzed-go/proto/authzed/api/v1 (interfaces: SchemaServiceClient)
//
// Generated by this command:
//
//	mockgen -destination=mock_schema_client_test.go -package=cmd github.com/authzed/authzed-go/proto/authzed/api/v1 SchemaServiceClient
//

// Package cmd is a generated GoMock package.
package cmd

import (
	context "context"
	reflect "reflect"

	v1 "github.com/authzed/authzed-go/proto/authzed/api/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockSchemaServiceClient is a mock of SchemaServiceClient interface.
type MockSchemaServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockSchemaServiceClientMockRecorder
	isgomock struct{}
}

// MockSchemaServiceClientMockRecorder is the mock recorder for MockSchemaServiceClient.
type MockSchemaServiceClientMockRecorder struct {
	mock *MockSchemaServiceClient
}

// NewMockSchemaServiceClient creates a new mock instance.
func NewMockSchemaServiceClient(ctrl *gomock.Controller) *MockSchemaServiceClient {
	mock := &MockSchemaServiceClient{ctrl: ctrl}
	mock.recorder = &MockSchemaServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSchemaServiceClient) EXPECT() *MockSchemaServiceClientMockRecorder {
	return m.recorder
}

// ComputablePermissions mocks base method.
func (m *MockSchemaServiceClient) ComputablePermissions(ctx context.Context, in *v1.ComputablePermissionsRequest, opts ...grpc.CallOption) (*v1.ComputablePermissionsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ComputablePermissions", varargs...)
	ret0, _ := ret[0].(*v1.ComputablePermissionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ComputablePermissions indicates an expected call of ComputablePermissions.
func (mr *MockSchemaServiceClientMockRecorder) ComputablePermissions(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComputablePermissions", reflect.TypeOf((*MockSchemaServiceClient)(nil).ComputablePermissions), varargs...)
}

// DependentRelations mocks base method.
func (m *MockSchemaServiceClient) DependentRelations(ctx context.Context, in *v1.DependentRelationsRequest, opts ...grpc.CallOption) (*v1.DependentRelationsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DependentRelations", varargs...)
	ret0, _ := ret[0].(*v1.DependentRelationsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DependentRelations indicates an expected call of DependentRelations.
func (mr *MockSchemaServiceClientMockRecorder) DependentRelations(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DependentRelations", reflect.TypeOf((*MockSchemaServiceClient)(nil).DependentRelations), varargs...)
}

// DiffSchema mocks base method.
func (m *MockSchemaServiceClient) DiffSchema(ctx context.Context, in *v1.DiffSchemaRequest, opts ...grpc.CallOption) (*v1.DiffSchemaResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DiffSchema", varargs...)
	ret0, _ := ret[0].(*v1.DiffSchemaResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DiffSchema indicates an expected call of DiffSchema.
func (mr *MockSchemaServiceClientMockRecorder) DiffSchema(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DiffSchema", reflect.TypeOf((*MockSchemaServiceClient)(nil).DiffSchema), varargs...)
}

// ReadSchema mocks base method.
func (m *MockSchemaServiceClient) ReadSchema(ctx context.Context, in *v1.ReadSchemaRequest, opts ...grpc.CallOption) (*v1.ReadSchemaResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ReadSchema", varargs...)
	ret0, _ := ret[0].(*v1.ReadSchemaResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadSchema indicates an expected call of ReadSchema.
func (mr *MockSchemaServiceClientMockRecorder) ReadSchema(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadSchema", reflect.TypeOf((*MockSchemaServiceClient)(nil).ReadSchema), varargs...)
}

// ReflectSchema mocks base method.
func (m *MockSchemaServiceClient) ReflectSchema(ctx context.Context, in *v1.ReflectSchemaRequest, opts ...grpc.CallOption) (*v1.ReflectSchemaResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ReflectSchema", varargs...)
	ret0, _ := ret[0].(*v1.ReflectSchemaResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReflectSchema indicates an expected call of ReflectSchema.
func (mr *MockSchemaServiceClientMockRecorder) ReflectSchema(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReflectSchema", reflect.TypeOf((*MockSchemaServiceClient)(nil).ReflectSchema), varargs...)
}

// WriteSchema mocks base method.
func (m *MockSchemaServiceClient) WriteSchema(ctx context.Context, in *v1.WriteSchemaRequest, opts ...grpc.CallOption) (*v1.WriteSchemaResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WriteSchema", varargs...)
	ret0, _ := ret[0].(*v1.WriteSchemaResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WriteSchema indicates an expected call of WriteSchema.
func (mr *MockSchemaServiceClientMockRecorder) WriteSchema(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteSchema", reflect.TypeOf((*MockSchemaServiceClient)(nil).WriteSchema), varargs...)
}
